
```{r function code}
#dependencies
library(ggpubr)
#Helper Functions:----
#ARGS:
  #dt: dataframe/table which to use
  #depth: taxonomic rank which to stop percent calculations at, as a  character string (eg order, family, genus, etc.). 
  #filter_rank: if the query should be filtered for a specific taxonomic ranking (e.g. "order", "family:, etc.). defaults to NA, where no filter will be applied
  #filter_name: if filter rank is given, what is the name of the rank to filter by? (e.g. only look at obs which are hymenoptera = filter_rank "order", filter_name = "Hymenoptera")
#OUTPUT:
#function outputs a list of each taxon rank to the given depth, with each element being a rank. each element holds a vector of length 3, contaning character outputs
Percent_At_Taxon <- function(dt, depth = NA, filter_rank = NA, filter_name = NA){
  #coerce dt to data.table
  dt <- data.table::as.data.table(dt)
  #vector of taxonomic groups from available columns
  taxon_groups <- str_subset(colnames(dt), "(?<=taxon_)[:lower:]+(?=_name)")
  #remove NAs
  taxon_groups <- taxon_groups[!is.na(taxon_groups)]
  #clip taxon groups based on depth
  taxon_groups<- taxon_groups[1:ifelse(is.na(depth) == T, -1,str_which(taxon_groups,paste("_", depth, "_", sep = "")))]
  
  #is the query filtered?
  if(is.na(filter_rank) == TRUE){
    #calculate total number of observations from total number of rows
    TotalObs <- nrow(dt)
    #loop through taxon groups to calculate percent for each
    unfiltered_percent_list <- list()
    for(t in 1:length(taxon_groups)){
      #current rank query string
      current_query_string <- taxon_groups[t]
      #calculate total number of observations of given taxon group t
      TotalQueriedObs <-nrow(dt[dt[[current_query_string]] != ""])
      #calculate percent of observations at given rank
      PercentAtRank <- TotalQueriedObs/TotalObs*100
      #output results to list as vector
      unfiltered_percent_list[[t]] <- c(paste("Total Observations at given rank:", TotalQueriedObs),
                                        paste("Percent of Observations at given rank:", round(PercentAtRank, 2), "%"),
                                        paste("Total Observations in dataframe:", TotalObs))
    }
    #rename list elements
    names(unfiltered_percent_list) <- str_extract(taxon_groups, "(?<=taxon_)[:lower:]+(?=_name)")
    return(unfiltered_percent_list)
    
  } else { #if filtering is not NA 
    #remove superfluous taxon names according to given rank
    taxon_groups <- taxon_groups[str_which(taxon_groups, paste("_", filter_rank, "_", sep = "")):length(taxon_groups)]
    #query string for filtering
    filter_query_string <- paste("taxon",filter_rank,"name", sep = "_")
    #calculate total number of observations in the filtered set
    TotalObs <- nrow(dt[dt[[filter_query_string]] == filter_name])
    #loop through taxon groups to calculate percent for each
    filtered_percent_list <- list()
    for(t in 1:length(taxon_groups)){
      #current rank query string
      current_query_string <- taxon_groups[t]
      #calculate total number of observations of queried rank by filter
      TotalQueriedObs <- nrow(dt[dt[[current_query_string]] != "" & dt[[filter_query_string]] == filter_name])
      #calculate percent of observations at given rank
      PercentAtRank <- TotalQueriedObs/TotalObs*100
      #output results to list as vector
      filtered_percent_list[[t]] <- c(paste("Total Observations at given rank:", TotalQueriedObs),
                                    paste("Percent of Observations at given rank:", round(PercentAtRank, 2), "%"),
                                    paste("Total Observations in dataframe:", TotalObs))
    }
    #rename list elements
    names(filtered_percent_list) <- str_extract(taxon_groups, "(?<=taxon_)[:lower:]+(?=_name)")
    return(filtered_percent_list)
  }
 
}

#ARGS:
#dt: dataframe/table which to use
  #depth: taxonomic rank which to stop percent calculations at, as a  character string (eg order, family, genus, etc.). 
  #group_rank: if the query should be grouped for a specific taxonomic ranking (e.g. "order", "family:, etc.). defaults to order, and cannot be NA
  #threshold: numeric value from 0 - 100, indicating at what percent rank to accept (e.g., if threshold = .7 and coleoptera obsrvations have reached 75% depth to family, they will have a table made in the return list)
#OUTPUT:
#data frame containing all observations
tBox_Diversity <- function(dt, depth, threshold = 70, group_rank = "order"){
  #coerce dt to data.table
  dt <- data.table::as.data.table(dt)
  #create output list
  return_list <- list()
  #iterate through given group rank of dt, passing args to Percent_At_Taxon function
  for(t in 1:length(unique(dt[[paste("taxon_",group_rank,"_name", sep ="")]]))){
    #current group string
    current_taxobox <- unique(dt[[paste("taxon_",group_rank,"_name", sep ="")]])[t]
    #build list element
    #call Percent_at_taxon
    PAT_call <- Percent_At_Taxon(dt = dt, depth = depth, filter_rank = group_rank, filter_name = current_taxobox)
    
    #extract return values at the desired depth
    percent_t <- as.numeric(str_extract(PAT_call[depth][[1]][2], "[:digit:]+") )
    
    #check if desired threshold is passed
    if(is.na(percent_t) != T & percent_t > threshold){
      #add only elements which are at the given depth
      return_list[[t]] <- dt[dt[[paste("taxon_",group_rank,"_name", sep ="")]] == current_taxobox & dt[[paste("taxon_",depth,"_name", sep ="")]] != ""] %>% 
        as_tibble() %>%
      select(!longitude & !latitude & !positional_accuracy 
                & !description & !observed_on_string & !taxon_id & !id & !quality_grade & 
                  !tag_list  & !scientific_name & !species_guess) %>% 
      left_join(select(Veg_Data_wide, SiteRep, ends_with("Dec"), Sample_Time, Date), by = "SiteRep")  %>% 
      select( SiteRep,Method,Type ,Date, Sample_Time, ends_with("Dec"), starts_with("taxon"), FunctionalGroup, everything()) 
      #coerce to df
      return_list[[t]] <- as.tibble(return_list[[t]])
    } else {
      return_list[[t]]<- NA
    }
    names(return_list)[t] <- current_taxobox 
  }
  #remove null values
  return_list <- return_list[!is.na(return_list)]
  #bind rows together
  return_df <- bind_rows(return_list, .id = "id") %>%
    mutate(id = rank(id, ties.method = "min"))
  return(return_df)
}

#test
family_level <- tBox_Diversity(BugDiversity_RAW, depth = "family", threshold = 50)

ggplot(filter(family_level[["Araneae"]], taxon_family_name != "" & Site != "UC"), aes(x =taxon_family_name)) +
  geom_bar(position = "dodge") +facet_wrap(~Site, scales = "free") +
  theme_gaia() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) +
  scale_fill_viridis_d(begin = 0.1, end = 0.9)

genus_level <- tBox_Diversity(BugDiversity_RAW, depth = "genus", threshold = 50, group_rank = "subfamily")

ggplot(filter(genus_level[["Hymenoptera"]], taxon_genus_name != "" & Site != "UC"), aes(x =taxon_genus_name, fill = Rep)) +
  geom_bar(position = "dodge") +facet_wrap(~Site, scales = "free") +
  theme_gaia() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) +
  scale_fill_viridis_d(begin = 0.1, end = 0.9)

#theme function code----
theme_gaia = function(base_size =12){
  theme_pubr(base_family="sans") %+replace%
    theme(panel.background  = element_blank(),
      plot.background = element_rect(fill="transparent", colour=NA), 
      legend.background = element_rect(fill="transparent", colour=NA),
      legend.key = element_rect(fill="transparent", colour=NA),
      legend.text = element_text(size=base_size * 0.7),
      legend.title = element_text(size = base_size * 0.8, 
                                  face = "bold"),
      axis.text = element_text(size = base_size*0.85),
      axis.title = element_text(size = base_size * 1.2),
      plot.title.position = "panel",
      plot.caption.position = "panel",
      plot.title = element_text(
        size = base_size * 1.25,
        face = "bold", 
        hjust = 0.5,
        vjust = 1),
      plot.subtitle = element_text(
        size = base_size * 0.9,
        vjust = 1),
      plot.caption =  element_text(
        size = base_size*0.75,
        hjust = 0.5)
    )
  
}
```

```{rRaw BugData deep dive: spiders}
SpiderFams<- family_level[["Araneae"]] %>% group_by(SiteRep, taxon_family_name) %>% 
  summarise(FamCounts = n(),
            across(Type:LongitudeDec, unique)) 

SpiderFamWide <- SpiderFams %>% 
  pivot_wider(names_from = "taxon_family_name", values_from = "FamCounts", values_fill = 0) %>% 
  ungroup() %>% 
  mutate(Richness = hillR::hill_taxa(select(.,"Araneidae":"Dysderidae"), q =0), #hill Richness
         Shannon = hillR::hill_taxa(select(.,"Araneidae":"Dysderidae"), q =1), #Shannon-Weiner Index
         InvSimp = hillR::hill_taxa(select(.,"Araneidae":"Dysderidae"), q = 2), #Inverse Simpson Diversity Index
         )
  
SpFa_summ <- SpiderFams %>% 
  group_by(Type, taxon_family_name) %>% 
  mutate(meanFC = mean(FamCounts),
         seFC = sd(FamCounts)/sqrt(n()),
         meanST = mean(Sample_Time),
         seST = sd(Sample_Time)/sqrt(n())) %>% 
  summarise(across(meanFC:seST, unique))

SpFaW_summ <- SpiderFamWide %>% 
  group_by(Type) %>% 
  mutate(across(Richness:InvSimp, list(mean= mean, se = ~ sd(.x)/sqrt(n()))))
  
#abundance plots
ggplot(SpiderFams, aes(x = taxon_family_name, y = FamCounts, fill = SiteRep)) +
  geom_col(position = "dodge") +scale_fill_viridis_d() +
  theme_gaia(base_size = 15) +
  facet_grid(~Type, scales = "free", space = "free") +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45))  

ggplot(SpFa_summ, aes( x= taxon_family_name, y = meanFC, fill = Type, group =Type)) +
  geom_col(position = "stack")+ 
  facet_wrap(~Type, scales = "free_x") +scale_fill_viridis_d() +
  theme_gaia(base_size = 15) +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45))  +
  
  labs(title = " Abundance of Spider Families across site classes",
       x = "Family", y = "Average Abundance", fill = "Site Class")

#diversity indices
ggplot(SpFaW_summ, aes(x = SiteRep, y = Richness, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Richness_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Richness_mean, ymin = Richness_mean-2*Richness_se, ymax = Richness_mean+2*Richness_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

  
ggplot(SpFaW_summ, aes(x = SiteRep, y = Shannon, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Shannon_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Shannon_mean, ymin = Shannon_mean-2*Shannon_se, ymax = Shannon_mean+2*Shannon_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

ggplot(SpFaW_summ, aes(x = SiteRep, y = InvSimp, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = InvSimp_mean)) +
  geom_errorbar(aes(x = SiteRep, y = InvSimp_mean, ymin = InvSimp_mean-2*InvSimp_se, ymax = InvSimp_mean+2*InvSimp_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 
  
```

```{r coles}
ColeFams<- family_level[["Coleoptera"]] %>% 
  filter(FunctionalGroup != "") 

ColeFamWide <- ColeFams %>% 
  mutate(O_T = paste(taxon_family_name, FunctionalGroup)) %>% 
  ungroup() %>% 
  select(!FunctionalGroup & !taxon_family_name) %>% 
  pivot_wider(names_from = "O_T", values_from = "FamCounts", values_fill = 0) %>% 
  ungroup() %>% 
  mutate(Richness = hillR::hill_taxa(select(.,"Coccinellidae Predator":"Attelabidae Herbivore"), q =0), #hill Richness
         Shannon = hillR::hill_taxa(select(.,"Coccinellidae Predator":"Attelabidae Herbivore"), q =1), #Shannon-Weiner Index
         InvSimp = hillR::hill_taxa(select(.,"Coccinellidae Predator":"Attelabidae Herbivore"), q = 2), #Inverse Simpson Diversity Index
         )
  
CoFa_summ <- ColeFams %>% 
  group_by(Type, taxon_family_name) %>% 
  mutate(meanFC = mean(FamCounts),
         seFC = sd(FamCounts)/sqrt(n()),
         meanST = mean(Sample_Time),
         seST = sd(Sample_Time)/sqrt(n())) %>% 
  summarise(across(meanFC:seST, unique))

CoFaW_summ <- ColeFamWide %>% 
  group_by(Type) %>% 
  mutate(across(Richness:InvSimp, list(mean= mean, se = ~ sd(.x)/sqrt(n()))))



#abundance plots
ggplot(ColeFams, aes(x = taxon_family_name, fill = FunctionalGroup)) +
  geom_bar()+
  facet_grid(~Type, scales = "free", space = "free") + 
  theme_gaia(base_size = 15) +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) +
  scale_fill_viridis_d()

ggplot(CoFa_summ, aes( x= taxon_family_name, y = meanFC, fill = meanST, group =Type)) +
  geom_col(position = "dodge")+
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme_gaia(base_size = 15) +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

#diversity indices
ggplot(CoFaW_summ, aes(x = SiteRep, y = Richness, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Richness_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Richness_mean, ymin = Richness_mean-2*Richness_se, ymax = Richness_mean+2*Richness_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

  
ggplot(CoFaW_summ, aes(x = SiteRep, y = Shannon, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Shannon_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Shannon_mean, ymin = Shannon_mean-2*Shannon_se, ymax = Shannon_mean+2*Shannon_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

ggplot(CoFaW_summ, aes(x = SiteRep, y = InvSimp, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = InvSimp_mean)) +
  geom_errorbar(aes(x = SiteRep, y = InvSimp_mean, ymin = InvSimp_mean-2*InvSimp_se, ymax = InvSimp_mean+2*InvSimp_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 
  
```


```{r hemips}
HemipFams<- family_level[["Hemiptera"]] 
  filter(FunctionalGroup != "") 

HemipFamWide <- HemipFams %>% 
  mutate(O_T = paste(taxon_family_name, FunctionalGroup)) %>% 
  ungroup() %>% 
  select(!FunctionalGroup & !taxon_family_name) %>% 
  pivot_wider(names_from = "O_T", values_from = "FamCounts", values_fill = 0) %>% 
  ungroup() %>% 
  mutate(Richness = hillR::hill_taxa(select(.,"Cicadellidae Herbivore":"Triozidae Herbivore"), q =0), #hill Richness
         Shannon = hillR::hill_taxa(select(.,"Cicadellidae Herbivore":"Triozidae Herbivore"), q =1), #Shannon-Weiner Index
         InvSimp = hillR::hill_taxa(select(.,"Cicadellidae Herbivore":"Triozidae Herbivore"), q = 2), #Inverse Simpson Diversity Index
         )
  
HeFa_summ <- HemipFams %>% 
  group_by(Type, taxon_family_name) %>% 
  mutate(meanFC = mean(FamCounts),
         seFC = sd(FamCounts)/sqrt(n()),
         meanST = mean(Sample_Time),
         seST = sd(Sample_Time)/sqrt(n())) %>% 
  summarise(across(meanFC:seST, unique))

HeFaW_summ <- HemipFamWide %>% 
  group_by(Type) %>% 
  mutate(across(Richness:InvSimp, list(mean= mean, se = ~ sd(.x)/sqrt(n()))))



#abundance plots
ggplot(HemipFams, aes(x = taxon_family_name, fill = FunctionalGroup)) +
  geom_bar()+
  facet_grid(~Type, scales = "free", space = "free") + 
  theme_gaia(base_size = 15) +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) +
  scale_fill_viridis_d()
  

ggplot(HeFa_summ, aes( x= taxon_family_name, y = meanFC, fill = Type, group =Type)) +
  geom_col(position = "dodge")+
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_d() +
  theme_gaia(base_size = 15) +
  facet_grid(~Type, scales = "free", space = "free") +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

#diversity indices
ggplot(HeFaW_summ, aes(x = SiteRep, y = Richness, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Richness_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Richness_mean, ymin = Richness_mean-2*Richness_se, ymax = Richness_mean+2*Richness_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

  
ggplot(HeFaW_summ, aes(x = SiteRep, y = Shannon, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Shannon_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Shannon_mean, ymin = Shannon_mean-2*Shannon_se, ymax = Shannon_mean+2*Shannon_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

ggplot(HeFaW_summ, aes(x = SiteRep, y = InvSimp, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = InvSimp_mean)) +
  geom_errorbar(aes(x = SiteRep, y = InvSimp_mean, ymin = InvSimp_mean-2*InvSimp_se, ymax = InvSimp_mean+2*InvSimp_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 
  
```

```{rRaw BugData deep dive: hymens}
#with ants----
HymenFams<- family_level[["Hymenoptera"]]

HymenFamWide <- HymenFams %>% 
  pivot_wider(names_from = "taxon_family_name", values_from = "FamCounts", values_fill = 0) %>% 
  ungroup() %>% 
  mutate(Richness = hillR::hill_taxa(select(.,"Formicidae":"Platygastridae"), q =0), #hill Richness
         Shannon = hillR::hill_taxa(select(.,"Formicidae":"Platygastridae"), q =1), #Shannon-Weiner Index
         InvSimp = hillR::hill_taxa(select(.,"Formicidae":"Platygastridae"), q = 2), #Inverse Simpson Diversity Index
         )
  
HyFa_summ <- HymenFams %>% 
  group_by(Type, taxon_family_name) %>% 
  mutate(meanFC = mean(FamCounts),
         seFC = sd(FamCounts)/sqrt(n()),
         meanST = mean(Sample_Time),
         seST = sd(Sample_Time)/sqrt(n())) %>% 
  summarise(across(meanFC:seST, unique))

HyFaW_summ <- HymenFamWide %>% 
  group_by(Type) %>% 
  mutate(across(Richness:InvSimp, list(mean= mean, se = ~ sd(.x)/sqrt(n()))))
  
#abundance plots
ggplot(HyFa_summ, aes( x= taxon_family_name, y = meanFC, fill = Type, group =Type)) +
  geom_col(position = "dodge")+
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_d() +
  theme_gaia(base_size = 15) +
  facet_grid(~Type, scales = "free", space = "free") +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

#diversity indices
ggplot(HyFaW_summ, aes(x = SiteRep, y = Richness, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Richness_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Richness_mean, ymin = Richness_mean-2*Richness_se, ymax = Richness_mean+2*Richness_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

  
ggplot(HyFaW_summ, aes(x = SiteRep, y = Shannon, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Shannon_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Shannon_mean, ymin = Shannon_mean-2*Shannon_se, ymax = Shannon_mean+2*Shannon_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

ggplot(HyFaW_summ, aes(x = SiteRep, y = InvSimp, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = InvSimp_mean)) +
  geom_errorbar(aes(x = SiteRep, y = InvSimp_mean, ymin = InvSimp_mean-2*InvSimp_se, ymax = InvSimp_mean+2*InvSimp_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 
  
#without ants----
HymenFams<- family_level[["Hymenoptera"]] %>% filter(taxon_family_name != "Formicidae")

HymenFamWide <- HymenFams %>% 
  filter(taxon_family_name != "Formicidae") %>% 
  pivot_wider(names_from = "taxon_family_name", values_from = "FamCounts", values_fill = 0) %>% 
  ungroup() %>% 
  mutate(Richness = hillR::hill_taxa(select(.,"Ichneumonidae":"Platygastridae"), q =0), #hill Richness
         Shannon = hillR::hill_taxa(select(.,"Ichneumonidae":"Platygastridae"), q =1), #Shannon-Weiner Index
         InvSimp = hillR::hill_taxa(select(.,"Ichneumonidae":"Platygastridae"), q = 2), #Inverse Simpson Diversity Index
         )
  
HyFa_summ <- HymenFams %>% 
  group_by(Type, taxon_family_name) %>% 
  mutate(meanFC = mean(FamCounts),
         seFC = sd(FamCounts)/sqrt(n()),
         meanST = mean(Sample_Time),
         seST = sd(Sample_Time)/sqrt(n())) %>% 
  summarise(across(meanFC:seST, unique))

HyFaW_summ <- HymenFamWide %>% 
  group_by(Type) %>% 
  mutate(across(Richness:InvSimp, list(mean= mean, se = ~ sd(.x)/sqrt(n()))))
  
#abundance plots
ggplot(HyFa_summ, aes( x= taxon_family_name, y = meanFC, fill = Type, group =Type)) +
  geom_col(position = "dodge")+
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_d() +
  theme_gaia(base_size = 15) +
  facet_grid(~Type, scales = "free", space = "free") +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

#diversity indices
ggplot(HyFaW_summ, aes(x = SiteRep, y = Richness, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Richness_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Richness_mean, ymin = Richness_mean-2*Richness_se, ymax = Richness_mean+2*Richness_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

  
ggplot(HyFaW_summ, aes(x = SiteRep, y = Shannon, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Shannon_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Shannon_mean, ymin = Shannon_mean-2*Shannon_se, ymax = Shannon_mean+2*Shannon_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

ggplot(HyFaW_summ, aes(x = SiteRep, y = InvSimp, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = InvSimp_mean)) +
  geom_errorbar(aes(x = SiteRep, y = InvSimp_mean, ymin = InvSimp_mean-2*InvSimp_se, ymax = InvSimp_mean+2*InvSimp_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 
  
```

```{r just ants}
#JUST ants----
AntGenuses<- genus_level[["Hymenoptera"]] 

AntGWide <- AntGenuses %>% 
  pivot_wider(names_from = "taxon_genus_name", values_from = "FamCounts", values_fill = 0) %>% 
  ungroup() %>% 
  mutate(Richness = hillR::hill_taxa(select(.,"Aphaenogaster":"Lasius"), q =0), #hill Richness
         Shannon = hillR::hill_taxa(select(.,"Aphaenogaster":"Lasius"), q =1), #Shannon-Weiner Index
         InvSimp = hillR::hill_taxa(select(.,"Aphaenogaster":"Lasius"), q = 2), #Inverse Simpson Diversity Index
         )
  
AG_summ <- AntGenuses %>% 
  group_by(Type, taxon_genus_name) %>% 
  mutate(meanFC = mean(FamCounts),
         seFC = sd(FamCounts)/sqrt(n()),
         meanST = mean(Sample_Time),
         seST = sd(Sample_Time)/sqrt(n())) %>% 
  summarise(across(meanFC:seST, unique))

AGW_summ <- AntGWide %>% 
  group_by(Type) %>% 
  mutate(across(Richness:InvSimp, list(mean= mean, se = ~ sd(.x)/sqrt(n()))))
  
#abundance plots
ggplot(AG_summ, aes( x= taxon_genus_name, y = meanFC, fill = meanST, group =Type)) +
  geom_col(position = "dodge")+
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

#diversity indices
ggplot(AGW_summ, aes(x = SiteRep, y = Richness, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Richness_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Richness_mean, ymin = Richness_mean-2*Richness_se, ymax = Richness_mean+2*Richness_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

  
ggplot(AGW_summ, aes(x = SiteRep, y = Shannon, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = Shannon_mean)) +
  geom_errorbar(aes(x = SiteRep, y = Shannon_mean, ymin = Shannon_mean-2*Shannon_se, ymax = Shannon_mean+2*Shannon_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 

ggplot(AGW_summ, aes(x = SiteRep, y = InvSimp, fill = Sample_Time) ) +
  geom_col() +
  geom_point(aes(x = SiteRep, y = InvSimp_mean)) +
  geom_errorbar(aes(x = SiteRep, y = InvSimp_mean, ymin = InvSimp_mean-2*InvSimp_se, ymax = InvSimp_mean+2*InvSimp_se)) +
  facet_wrap(~Type, scales = "free") +scale_fill_viridis_c() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) 
 
```


```{r analysis control panel 1.0}
#dependencies----
require(viridisLite)
#executing main analyses----
source("RScripts/PlantDiversity.R")
source("RScripts/CanopyCover.R")
source("RScripts/AirQuality.R")
source("RScripts/BugDiversity_1.0.R") 
source("RScripts/GIS.R")

#merge data for plotting----
#all diversity scores
Full_DivScore_Data <- BugDiv_Indices %>%
  select(!("Fungivore-Coleoptera":"Predator-Neuroptera")) %>% 
  left_join(., select(Veg_Data_wide,SiteRep,
                      starts_with("Plant"), 
                      starts_with("Tree"),
                      starts_with("Veg")), by ="SiteRep") %>% 
  arrange(SiteRep)

#environmental data
FullEnviron_Data <- Veg_Data_wide %>% 
  select(SiteRep, Date, Sample_Time, PropTrees_Sampled, CanopyCoverPer) %>% 
  left_join(., select(GIS_Data, !geometry), by = "SiteRep") %>% 
  left_join(., AQ_Summary, by = "SiteRep") %>% 
  filter(is.na(AVG_PM2.5) != T) %>% 
  arrange(SiteRep)


#calculate PCAs of variables----
#anthropogenic factor
AnthroLandscape_PCA <-prcomp(filter(select(FullEnviron_Data, 
                                           contains("1km"), 
                                           contains("Annum"), 
                                           contains("PM")), is.na(AVG_PM2.5) != T), scale. = T)
#correl plot 
corrplot::corrplot(AnthroLandscape_PCA$rotation,col = colorRampPalette(viridis(50))(50),#number of breaks in brackets
                   addCoef.col = "black", tl.col = "black")



#

#correl between vars
cor_environLandscape <- cor(filter(select(FullEnviron_Data, 
                                           contains("1km"), 
                                           contains("Annum"), 
                                           contains("PM")), is.na(AVG_PM2.5) != T))
corrplot::corrplot(cor_environLandscape)
#scree plot
factoextra::fviz_eig(AnthroLandscape_PCA)


#fn abundances
Bug_PCA <-prcomp(select(BugDiv_Abundance,"Fungivore-Coleoptera":"Predator-Neuroptera"), scale. = T)
#correl plot
corrplot::corrplot(Bug_PCA$rotation,col = colorRampPalette(viridis(50))(50),#number of breaks in brackets
               tl.col = "black")
#correl between vars
bug_cor <- cor(select(BugDiv_Abundance, starts_with("Predator") | starts_with("Herbivore")))
corrplot::corrplot(bug_cor,col = colorRampPalette(viridis(50))(50),#number of breaks in brackets
               tl.col = "black")
#screeplot
factoextra::fviz_eig(Bug_PCA)

#merge PCAs into diversity table
MergedData <- tibble(FullEnviron_Data,
                     rename(select(as_tibble(AnthroLandscape_PCA$x), PC1, PC2), Landscape_PC1 = PC1, Landscape_PC2 = PC2)) %>% 
  left_join(Full_DivScore_Data, by = "SiteRep") %>% 
  filter(is.na(AVG_PM2.5) != T) %>% 
  mutate(Rep = as.factor(str_extract(SiteRep, "[:digit:]")),
         Type = case_when(str_detect(SiteRep, "^U") == T ~ "Urban",
                          str_detect(SiteRep, "^S") == T ~ "Urban",
                          str_detect(SiteRep, "^R" )== T ~ "Rural"),
         Date = as.ordered(Date))



ggplot(MergedData, aes( x = Landscape_PC1, y = as.POSIXct(Date), fill = Type, shape = Rep)) +
  geom_vline(aes(xintercept = 0),linetype = 2) +
  geom_point(size = 5) +
  scale_fill_manual(values = c('#77fffa',"#ff638a") , guide ='none')+
  scale_shape_manual(values = c(21,22)) +
  theme_gaia(base_size = 25)  +
  labs(title = "Clustering \nby Urbanization factor",x = "PC1 (74%)", shape = "Replicate", y = "Date", fill ="Site")

```
### Stats:
```{r statistics}
#linear modelling time!!!


FnGORichness_Model<- glm(data = MergedData, 
            Total_Richness ~ Type + VegRichness + Rep,
            family = "poisson")
summary(FnGORichness_Model)
step(FnGORichness_Model)

ORichness_Model<- glm(data = MergedData, 
            Order_Richness ~ Type + VegRichness + Rep,
            family = "poisson")
summary(ORichness_Model)
FnGRichness_Model<- glm(data = MergedData, 
            FnG_Richness ~ Type + VegRichness + Rep,
            family = "poisson")
summary(FnGRichness_Model)

Shannon_Model <- glm(data = MergedData,
                     FnGO_Shannon ~ Landscape_PC1+VegShannon + Date)
summary(Shannon_Model)
#weirdo elmer
Shannon_Model <- lme4::lmer(data = MergedData,
                     FnGO_Shannon ~ Landscape_PC1 * VegShannon  + (1|Rep))
summary(Shannon_Model)

Even_Model<- glm(data = MergedData, 
            FnGO_Evenness ~ Landscape_PC1 + VegEvenness + Rep)
summary(Even_Model)
InvSimp_Model<- glm(data = MergedData, 
            FnGO_InvSimp ~ Landscape_PC1 + VegInvSimp +AVG_PM2.5 +AVG_TEMP + AVG_HUMID + Rep)
summary(InvSimp_Model)

#c
Richness_Tree<- partykit::ctree(data = MergedData, 
            Total_Richness ~ AVG1km_ALAN + AVG1km_ISC +AVG1km_CC + VegRichness +AVG_PM2.5 +AVG_TEMP + AVG_HUMID + Rep)
partykit::plot.party(Richness_Tree)
```

```{r plotting}
#overall abundance barplot----
ggplot(MergedData, aes(y = FnGO_Shannon, x = Date, fill = as.character(Date))) +
    geom_smooth(aes(fill = Date), method = "lm", se = F, color ="black", linetype = 2 ) +
  geom_point(shape = 21, size = 3) +
  scale_fill_viridis_d() +
    theme_gaia()

BDA <- BugDiv_Decent %>% 
  group_by(FunctionalGroup, Order) %>% 
  summarise(FNGO_ct = n()) %>% 
  group_by(FunctionalGroup) %>% 
  mutate(propFNGO = FNGO_ct/sum(FNGO_ct),
         total = sum(FNGO_ct))

BDA_Labels <- BDA %>% 
  group_by(FunctionalGroup) %>% 
  summarise(total = unique(total)) %>% 
  mutate(label = paste(FunctionalGroup,"n =", total))

BDAL <- c(Detritivore = "Detritivore n = 44",
          Fungivore = "Fungivore n = 3",
          Herbivore ="Herbivore n = 215",
          Omnivore ="Omnivore n = 552",
          Parasitoid = "Parasitoid n = 38",
          Predator= "Predator n = 381")
#all feeding guilds
ggplot(BDA, aes(x = tidytext::reorder_within(Order, propFNGO, FunctionalGroup) 
                ,y =propFNGO, fill = Order, group = Order)) +
  geom_col() + 
  facet_grid(~FunctionalGroup, scales = "free", space = "free", labeller = labeller(FunctionalGroup = BDAL)) +
  theme_gaia(base_size = 18) +
  tidytext::scale_x_reordered() +
  scale_fill_viridis_d() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) +
  labs(title = "Relative Abundance of Arthropod Orders Between Feeding Guilds",
       x = "Order", y = "% Abundance") 

#herbs, omnis, and preds
ggplot(filter(BDA, FunctionalGroup == "Omnivore" | FunctionalGroup == "Predator"| FunctionalGroup == "Herbivore"), aes(x = tidytext::reorder_within(Order, propFNGO, FunctionalGroup) 
                ,y =propFNGO, fill = Order, group = Order)) +
  geom_col() + 
  facet_wrap(~FunctionalGroup, scales = "free", nrow = 1, labeller = labeller(FunctionalGroup = BDAL)) +
  theme_gaia(base_size = 18) +
  tidytext::scale_x_reordered() +
  scale_fill_viridis_d() +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) +
  labs(title = "Relative Abundance of Arthropod Orders\n Between Feeding Guilds",
       x = "Order", y = "% Abundance") 

#abundances by siterep
BDB <- BugDiv_Decent %>% 
  group_by(Type, FunctionalGroup, Order) %>% 
  summarise(FNGOT_ct = n()) %>% 
  group_by(FunctionalGroup, Type) %>% 
  mutate(propFNGOT = FNGOT_ct/sum(FNGOT_ct),
         total = sum(FNGOT_ct))

ggplot(BDB, aes(x =Type, y = propFNGOT, fill = Order )) +
  geom_col(position = "stack") +
  theme_gaia(25) +
  facet_grid(~FunctionalGroup, scales = "free", space = "free", labeller = labeller(FunctionalGroup = BDAL)) +
  theme( axis.text.x = element_text(angle = 33, vjust = 0.45)) +
  scale_fill_viridis_d() +  labs(title = "Arthropod Functional Communities\n Across Urbanization", x = "",
        y = "% Abundance")

ggplot(BDB, aes(x =tidytext::reorder_within(Order, propFNGOT, Type), y = propFNGOT, fill = Order )) +
  geom_col(position = "dodge") +
  theme_gaia(16) +
  tidytext::scale_x_reordered() +
  facet_grid(~FunctionalGroup, scales = "free", space = "free", labeller = labeller(FunctionalGroup = BDAL)) +
  theme( axis.text.x = element_text(angle = 66, vjust = 0.45)) +
  scale_fill_viridis_d() +
  labs(title = "Relative abundance of Arthropod orders between feeding guilds and sites",
       x = "Order", y = "% Abundance")

#order richness by subjective----
MergedData1 <- MergedData %>% 
  group_by(Type) %>% 
  mutate(OR_se = sd(Order_Richness)/sqrt(n())) %>% 
  summarise(Order_Richness = mean(Order_Richness),
            OR_se = mean(OR_se))

ggplot(MergedData1, aes(x = Type, y = Order_Richness, fill = Type)) +
  geom_errorbar(aes(y = Order_Richness, 
                    ymin = Order_Richness-2*OR_se, 
                    ymax = Order_Richness+2*OR_se)) +
  geom_point(size = 2.5, shape = 21)+
  theme_gaia() +
  scale_fill_viridis_d(begin = 0.2, end = 0.8)

ggplot(MergedData, aes(x = Landscape_PC1, fill = Type)) +geom_bar()


```

```{r mapping}
ggplot() +
  geom_sf(data = NY_County_Shorelines, fill = "tan") +
  geom_sf(data = CityPark_Shapes, fill = "green") +
  coord_sf(xlim = c(587937,613293), ylim= c(4510475,4528568))
```

